{
 "title": "Custom_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "city",
    "query": {
     "query": "label_values(weather_temperature_c,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Максимальный ветер за 1 час",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(weather_wind_speed_ms{city=~\"$city\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура за 6 часов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_c{city=~\"$city\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Снег за 1ч",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "clamp_min(weather_snow_1h_mm{city=~\"$city\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Осадки за 1ч",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(weather_rain_1h_mm{city=~\"$city\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Облачность",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_clouds_pct{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ветер: “рваность” за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "stddev_over_time(weather_wind_speed_ms{city=~\"$city\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ветер",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "weather_wind_speed_ms{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Влажность",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_humidity_pct{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Давление",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_pressure_hpa{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Разница (ощущается − факт)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "weather_feels_like_c{city=~\"$city\"} - weather_temperature_c{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ощущается как",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "weather_feels_like_c{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "weather_temperature_c{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}