{
 "title": "PostgreSQL Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pg_instance",
    "label": "PostgreSQL instance",
    "query": {
     "query": "label_values(pg_up{job=\"postgres-exporter\"},instance)"
    }
   },
   {
    "name": "pg_database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (datname) (\r\n  pg_stat_user_tables_n_live_tup{instance=~\"$pg_instance\", datname=~\"$pg_database\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total rows & tables A Кол-во живых строк по БД",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  pg_stat_user_tables_n_live_tup{instance=~\"$pg_instance\", datname=~\"$pg_database\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks per second (Bar/TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_deadlocks{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows fetched per second (TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_tup_fetched{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)\r\n",
     "legendFormat": "Fetched {{datname}}"
    }
   ]
  },
  {
   "title": "Tuples changed per second (insert+update+delete) (TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_tup_inserted{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n  +\r\n  rate(pg_stat_database_tup_updated{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n  +\r\n  rate(pg_stat_database_tup_deleted{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)\r\n",
     "legendFormat": "DML {{datname}}"
    }
   ]
  },
  {
   "title": "QPS/TPS (transactions per second) (TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_xact_commit{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n  +\r\n  rate(pg_stat_database_xact_rollback{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)\r\n",
     "legendFormat": "QPS {{datname}}."
    }
   ]
  },
  {
   "title": "Disk hit bytes/s (TS) — «чтение из кеша»",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "8 * 1024 * sum by (datname) (\r\n  rate(pg_stat_database_blks_hit{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)\r\n",
     "legendFormat": "Cache {{datname}}"
    }
   ]
  },
  {
   "title": "Disk read bytes/s (TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "8 * 1024 * sum by (datname) (\r\n  rate(pg_stat_database_blks_read{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m])\r\n)\r\n",
     "legendFormat": "Read {{datname}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio (%) (TS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum by (datname) (rate(pg_stat_database_blks_hit{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m]))\r\n  /\r\n  (\r\n    sum by (datname) (rate(pg_stat_database_blks_hit{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m]))\r\n    +\r\n    sum by (datname) (rate(pg_stat_database_blks_read{instance=~\"$pg_instance\", datname=~\"$pg_database\"}[5m]))\r\n  )\r\n)\r\n",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database size (GB) (Bar/Stat)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=~\"$pg_instance\", datname=~\"$pg_database\"} / 1e9\r\n",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Uptime (TS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"postgres-exporter\", instance=~\"$pg_instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connections (Gauge/Stat)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  pg_stat_activity_count{instance=~\"$pg_instance\", datname=~\"$pg_database\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum by (datname, state) (\r\n  pg_stat_activity_count{instance=~\"$pg_instance\", datname=~\"$pg_database\"}\r\n)",
     "legendFormat": "{{datname}} / {{state}}"
    }
   ]
  }
 ]
}