{
 "title": "Windows explorer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(up,instance)" } },
   {
    "name": "volume",
    "label": "volume",
    "query": {
     "query": "label_values(windows_logical_disk_free_bytes,volume)"
    }
   },
   {
    "name": "nic",
    "label": "Network adapter",
    "query": {
     "query": "label_values(windows_net_bytes_total,$nic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active services",
   "type": "table",
   "description": "Таблица всех активных сервисов с полями name, display_name, run_as.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "windows_service_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services by run_as",
   "type": "barchart",
   "description": "Количество системных сервисов по типу аккаунта (LocalSystem, NetworkService и т.д.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (run_as) (windows_service_info)\r\n",
     "legendFormat": "{{run_as}}"
    }
   ]
  },
  {
   "title": "Network in/out traffic",
   "type": "timeseries",
   "description": "Общий сетевой трафик (вход+выход), bytes/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (nic) (rate(windows_net_bytes_total[5m]))",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Disk write speed",
   "type": "timeseries",
   "description": "Скорость записи на диск, bytes/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (volume) (rate(windows_logical_disk_write_bytes_total[5m]))\r\n",
     "legendFormat": "Write - {{volume}}"
    }
   ]
  },
  {
   "title": "Disk read speed",
   "type": "timeseries",
   "description": "Скорость чтения с диска, bytes/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (volume) (rate(windows_logical_disk_read_bytes_total[5m]))\r\n",
     "legendFormat": "Read - {{volume}}"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "stat",
   "description": "Свободное место по каждому диску, GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes / 1e9\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit pressure",
   "type": "gauge",
   "description": "Давление на память",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * windows_memory_committed_bytes / windows_memory_commit_limit\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Использование оперативной памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - windows_memory_available_bytes / windows_memory_physical_total_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 * (1 - sum by (core) (rate(windows_cpu_time_total{mode=\"idle\"}[5m])) / sum by (core) (rate(windows_cpu_time_total[5m])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 * (1 - sum(rate(windows_cpu_time_total{mode=\"idle\"}[5m]))\r\n          / sum(rate(windows_cpu_time_total[5m])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}